default: &default
  secret_token:
  ga_account:
  disqus_developer: 1
  disqus_shortname:
  default_title:
  default_description:
  admin_email:
  google_client_id:
  google_client_secret:
  github_client_id:
  github_client_secret:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  disqus_developer: 0
