default: &default
  origin:
  secret_token:
  secret_key_base:
  ga_account:
  disqus_developer: 1
  disqus_shortname:
  default_title:
  default_description:
  admin_email:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  disqus_developer: 0
