default: &default
  secret_token:
  ga_account:
  disqus_developer: 1
  disqus_shortname:
  default_title:
  default_description:
  google_client_id:
  google_client_secret:
  twitter_consumer_key:
  twitter_consumer_secret:
  github_client_id:
  github_client_secret:
  renren_api_key:
  renren_secret_key:
  douban_api_key:
  douban_secret:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  disqus_developer: 0
