default: &default
  secret_token:
  ga_account:
  disqus_developer: 1
  disqus_shortname:
  default_title:
  default_description:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  disqus_developer: 0
